# SPDX-FileCopyrightText: © 2023 Technical University of Munich, Chair of Connected Mobility
# SPDX-FileCopyrightText: © 2023 Siemens AG
# SPDX-License-Identifier: MIT
edition = "2024"
max_width = 150