[general]
domain_register_url = "http://0.0.0.0:7002"
subscription_refresh_interval_sec = 2
domain_id = "domain-7000"
orchestrator_url = "http://0.0.0.0:7000"
orchestrator_url_announced = "http://0.0.0.0:7000"
node_register_url = "http://0.0.0.0:7003"

[baseline]
orchestration_strategy = "Random"

[proxy]
proxy_type = "Redis"
redis_url = "redis://redis:6379"
proxy_gc_period_seconds = 0

[proxy.dataset_settings]
dataset_path = "./data/dda_"  # prefix
append = false
additional_fields = "a,b"
additional_header= "h_a,h_b"