[general]
node_id = "f6abb838-0225-4c97-a106-a3dca3a3828b"
agent_url = "http://127.0.0.1:7027"
agent_url_announced = "http://127.0.0.1:7027"
invocation_url = "http://127.0.0.1:7028"
invocation_url_announced = "http://127.0.0.1:7028"
node_register_url = "http://127.0.0.1:7004"
subscription_refresh_interval_sec = 2

[telemetry]
metrics_url = "http://127.0.0.1:7029"
performance_samples = false

[wasm_runtime]
enabled = true

[user_node_capabilities]
num_cpus = 1
model_name_cpu = "rpi-cpu"
clock_freq_cpu = 3504.0
num_cores = 4
mem_size = 8192
labels = ["rpi"]
is_tee_running = false
has_tpm = false
disk_tot_space = 256982
num_gpus = 0
model_name_gpu = ""
mem_size_gpu = 0
