# SPDX-FileCopyrightText: Â© 2024 Siemens AG
# SPDX-License-Identifier: MIT
[workspace]

[profile.release]
lto = true
opt-level = "s"

[package]
name = "check_temperature"
version = "0.1.0"
authors = ["Lukasz Zalewski <zalewski.lukasz@siemens.com>", "Saurabh Singh <narayan.singh@siemens.com>", "Markus Sauer <markussauer@siemens.com>"]
edition = "2021"

[lib]
name = "check_temperature"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
edgeless_function = { path = "../../../../edgeless_function" }
edgeless_http = { path = "../../../../edgeless_http" }
log = "0.4"
